# Generated by Django 4.2.16 on 2026-04-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="სათაური")),
                ("description", models.TextField(verbose_name="აღწერა")),
                (
                    "technologies",
                    models.CharField(max_length=300, verbose_name="ტექნოლოგიები"),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="ბმული")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        verbose_name="სურათი",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="რიგითობა")),
            ],
            options={
                "verbose_name": "პროექტი",
                "verbose_name_plural": "პროექტები",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="სათაური")),
                ("description", models.TextField(verbose_name="აღწერა")),
                (
                    "icon",
                    models.CharField(
                        help_text="Lucide icon name or SVG path",
                        max_length=100,
                        verbose_name="ხატულა",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="რიგითობა")),
            ],
            options={
                "verbose_name": "სერვისი",
                "verbose_name_plural": "სერვისები",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="სახელი")),
                ("email", models.EmailField(max_length=254, verbose_name="ელ-ფოსტა")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ტელეფონი"
                    ),
                ),
                ("message", models.TextField(verbose_name="შეტყობინება")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.service",
                        verbose_name="სერვისი",
                    ),
                ),
            ],
            options={
                "verbose_name": "დაჯავშნა",
                "verbose_name_plural": "დაჯავშნები",
            },
        ),
    ]
