# Generated by Django 4.2.16 on 2026-04-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_faq_project_problem_project_result_project_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="კლიენტის სახელი"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ელ-ფოსტა")),
                ("date", models.DateField(verbose_name="თარიღი")),
                ("time_slot", models.CharField(max_length=20, verbose_name="დრო")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="სტატუსი",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date", "time_slot"],
                "unique_together": {("date", "time_slot")},
            },
        ),
    ]
