# Generated by Django 4.2.16 on 2026-04-06 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_appointment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Booking", "verbose_name_plural": "Bookings"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["order"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["order"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Client Name"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time_slot",
            field=models.CharField(max_length=20, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.service",
                verbose_name="Service",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=255, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="project",
            name="problem",
            field=models.TextField(blank=True, null=True, verbose_name="Problem"),
        ),
        migrations.AlterField(
            model_name="project",
            name="result",
            field=models.TextField(blank=True, null=True, verbose_name="Result"),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="solution",
            field=models.TextField(blank=True, null=True, verbose_name="Solution"),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.CharField(max_length=300, verbose_name="Technologies"),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                help_text="Lucide icon name or SVG path",
                max_length=100,
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
    ]
