# Generated by Django 4.2.16 on 2026-04-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_alter_booking_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(blank=True, null=True, verbose_name="Answer (EN)"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Question (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(verbose_name="პასუხი"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=255, verbose_name="კითხვა"),
        ),
    ]
