# Generated by Django 4.2.16 on 2026-04-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_faq_answer_en_faq_question_en_alter_faq_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="phone",
            field=models.CharField(default="", max_length=20, verbose_name="Phone"),
        ),
    ]
