# Generated by Django 4.2.16 on 2026-04-07 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_appointment_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(verbose_name="პასუხი"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_en",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Answer (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="problem",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Problem"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="result",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Result"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="solution",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Solution"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="აღწერა"),
        ),
    ]
