# Generated by Django 4.2.16 on 2026-04-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_alter_faq_answer_alter_faq_answer_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="კლიენტის სახელი"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="პოზიცია / თანამდებობა"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="კომპანია"
                    ),
                ),
                ("text", models.TextField(verbose_name="გამოხმაურება")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="ფოტო",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="გამოჩნდეს საიტზე"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="რიგითობა")),
            ],
            options={
                "verbose_name": "შეფასება",
                "verbose_name_plural": "შეფასებები (Testimonials)",
                "ordering": ["order"],
            },
        ),
    ]
